#!/usr/bin/env python3
"""
Derives when each catalogue link was first added, for the "Newest" catalogue order.

Links in data/osint_data.json carry no date, but git history does: this walks every commit that
touched the file, oldest first, and records the commit time at which each URL first appeared.
Links in the working tree that are not committed yet are stamped with the current time.

Writes data/link_dates.json and data/link_dates.js (the .js twin lets index.html work when opened
straight from disk, like data/osint_data.js). Re-run after adding links:

    python build_link_dates.py
"""
import json
import os
import subprocess
import time

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_REL = 'data/osint_data.json'
OUT_JSON = os.path.join(ROOT_DIR, 'data', 'link_dates.json')
OUT_JS = os.path.join(ROOT_DIR, 'data', 'link_dates.js')


def _urls(data):
    for col in data.get('columns', []):
        for widget in col.get('widgets', []):
            for link in widget.get('links', []):
                if link.get('url'):
                    yield link['url']


def _git(*args):
    return subprocess.run(['git', *args], cwd=ROOT_DIR, capture_output=True, text=True, check=True).stdout


def build():
    first_seen = {}
    history = _git('log', '--reverse', '--format=%H %ct', '--', DATA_REL).split('\n')
    for line in filter(None, history):
        sha, ts = line.split()
        try:
            data = json.loads(_git('show', f'{sha}:{DATA_REL}'))
        except (subprocess.CalledProcessError, ValueError):
            continue  # file deleted or unparsable at this commit
        for url in _urls(data):
            first_seen.setdefault(url, int(ts))

    with open(os.path.join(ROOT_DIR, DATA_REL), encoding='utf-8') as f:
        current = json.load(f)
    now = int(time.time())
    # Only links still in the catalogue; anything not yet committed counts as added now.
    dates = {url: first_seen.get(url, now) for url in _urls(current)}

    with open(OUT_JSON, 'w', encoding='utf-8') as f:
        json.dump(dates, f, indent=0, sort_keys=True)
        f.write('\n')
    with open(OUT_JS, 'w', encoding='utf-8') as f:
        f.write('// Generated by build_link_dates.py - first-seen time (unix seconds) of each catalogue link.\n')
        f.write('window.BUBBSY_LINK_DATES = ')
        json.dump(dates, f, indent=0, sort_keys=True)
        f.write(';\n')
    distinct = len(set(dates.values()))
    print(f'link_dates: {len(dates)} links across {distinct} distinct add times -> {OUT_JSON}')


if __name__ == '__main__':
    build()
